// <auto-generated />
namespace Willians.LojaVirtual.Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CriaClienteDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriaClienteDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201705090256410_CriaClienteDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
